anonymous/urls.py
from django.urls import path
# from . import views
from .views import HomeView, ArticleView, AddView ,EditView ,RemoveView, CategoryView , LikeView , BookView, BookView2, ProfileView,CommentView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.home ,name="home" ),
    path('',HomeView.as_view(),name="home"),

    path('article/<int:pk>/', ArticleView.as_view(), name='detail_view'),

    path('share/' , AddView.as_view(), name="share" ),

    path('article/edit/<int:pk>/',EditView.as_view(),name="edit" ),

    path('article/delete/<int:pk>/',RemoveView.as_view(),name="delete" ),

    path('category/<str:cats>/', CategoryView , name='category'),

    path('like/<int:pk>',LikeView , name="like_post"),

    path('book/<int:pk>',BookView , name="book_post"),

    path('bookmark/<int:pk>/',BookView2,name="bookmark"),

    path('profile/<int:pk>/', ProfileView ,name="profile"),

    path('article/<int:pk>/comment',CommentView.as_view(), name="commentt")

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# path('bookmark/<int:cats>/',BookView , name="book_post"),

anonymousme/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('anonymous.urls')),
    path('bluffers/',include('django.contrib.auth.urls')),
    path('bluffers/',include('bluffers.urls')),
]

bluffers/urls.py
from django.urls import path
from .views import UserRegistrationView
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('register/', UserRegistrationView.as_view(),name="register"),

    path('login/', LoginView.as_view(),name= "login"),


]

anonymous/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from datetime import datetime,date
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        # return reverse('detail_view', args=(str(self.id),))
        return reverse('home')

class Message(models.Model):
    title= models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    postdate = models.DateField(auto_now_add= True)
    categories = models.CharField(max_length=25,choices=Category.objects.all().values_list('name','name'),default="begining of an era")
    image = models.ImageField(upload_to="message/memories", default="",null=True,blank=True)
    like = models.ManyToManyField(User,related_name='blog_posts')
    book = models.ManyToManyField(User,related_name='blog_book')

    def __str__(self) -> str:
        return self.title+' | '+str(self.author)
    
    def get_absolute_url(self):
        # return reverse('detail_view', args=(str(self.id),))
        return reverse('home')
    
    def total_likes(self):
        return self.like.count()
    
choices = Category.objects.all()
choices_list = []

for item in choices:
    choices_list.append(item)

# bchoices = Message.objects.all().values_list('author', flat=True).distinct()
# bchoices_list = []
# for item in bchoices:
#     bchoices_list.append(item)

    
class Comment(models.Model):
    post = models.ForeignKey(Message,related_name="comments",on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return '%s - %s' % (self.post.title ,self.name )

bluffers/models.py
from django.db import models

# Create your models here.

anonymous/views.py
from typing import Any, Dict
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView, DetailView , CreateView, UpdateView, DeleteView
from .models import Message,choices_list,Comment
from django.urls import reverse_lazy ,reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import models


# Create your views here.
# def home(request):
#     return render(request,'index.html',{})


class HomeView(ListView):
    model = Message
    template_name = 'index.html'
    ordering=['-id']


class ArticleView(DetailView):
    model = Message
    template_name = 'article_details.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        stuff = get_object_or_404(Message, id = self.kwargs['pk'])
        context = super(ArticleView , self).get_context_data(**kwargs)
        total_likes = stuff.total_likes()
        context["total_likes"] = total_likes
        liked = False
        booked = False
        if stuff.like.filter(id = self.request.user.id).exists():
            liked = True
        if stuff.book.filter(id = self.request.user.id).exists():
            booked = True
        context["booked"] = booked
        context["liked"] = liked
        return context


class AddView(CreateView):
    model= Message
    template_name= 'addpost.html'
    fields= ['author','title','body','categories','image']

class CommentView(CreateView):
    model= Comment
    template_name= 'addcomment.html'
    fields = '__all__'
    success_url = reverse_lazy('home')

    def get_context_data(self,**kwargs):
        context = super(CreateView , self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

class EditView(UpdateView):
    model= Message
    template_name= 'update.html'
    fields= ['title','body','categories','image']

class RemoveView(DeleteView):
    model = Message
    template_name = 'delete.html'
    success_url = reverse_lazy('home')

def CategoryView(request,cats):
    category_posts = Message.objects.filter(categories = cats)
    return render(request, 'categories.html', {'cats': cats , 'category_posts': category_posts , 'choices': choices_list})

@login_required
def LikeView(request,pk):
    post = get_object_or_404(Message, id = pk)
    liked =False
    if post.like.filter(id = request.user.id).exists():
        post.like.remove(request.user)
        liked = False
    else:
        post.like.add(request.user) 
        liked= True
    return HttpResponseRedirect(reverse('detail_view', args=[str(pk)]))

@login_required
def BookView(request,pk):
    post = get_object_or_404(Message, id = pk)
    if post.book.filter(id = request.user.id).exists():
        post.book.remove(request.user)
    else:
        post.book.add(request.user)
    return HttpResponseRedirect(reverse('detail_view', args=[str(pk)]))

# def BookView(request,cats):
#     category_posts = Message.objects.filter(book = cats)
#     return render(request, 'bookmarks.html', {'cats': cats , 'category_posts': category_posts , 'choices': bchoices_list})

def BookView2(request,pk):
    bookmark_posts = Message.objects.filter(book = pk)
    return render(request, 'bookmarks.html',{'id': pk , 'bookmark_posts':bookmark_posts })

def ProfileView(request,pk):
    bookmark_posts = Message.objects.filter(author = pk)
    user = get_object_or_404(User, id=pk)
    bluffs = bookmark_posts.count()
    return render(request, 'profile.html',{'id': pk , 'bookmark_posts':bookmark_posts , 'bluffs': bluffs , 'userr' : user })

bluffers/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
# Create your views here.

class UserRegistrationView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('login')


class UserLoginView(LoginView):
    template_name = 'registration/login.html'
    success_url = reverse_lazy('home')

anonymous/templates/addcomment.html
{% extends 'base.html' %}

{% block content %}

<div class="tweetBox" >
    <form method="POST" style="display: flex; flex-direction: column;">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button class="tweet_btn" type="submit" name="share" style="text-align: center;margin-inline: auto;padding-inline: 15vw;"><i class="fa-solid fa-infinity" style="background-color: rgba(240, 248, 255, 0);"></i>&nbsp;&nbsp;add comment</button>
    </form>
</div>

<div style="text-align: right;padding-inline-end: 10px;padding-top: 10px;">
    <a class="tweet_btn" href="{% url 'home' %}" style=" margin-inline-end: 0.5vw; text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward" style="background-color: rgba(0, 0, 0, 0);"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
<script>
 document.addEventListener("DOMContentLoaded", function() {

        let comment = document.getElementById("id_post");
        console.log(comment);
        comment.value = "{{ pk }}";
        comment.style.display = "none";
        let lc = document.querySelector("label[for='id_post']");
        lc.style.display = "none";

    });
</script>
{% endblock %}

anonymous/templates/addpost.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
{% block content %}

<div class="tweetBox" >
    <form method="POST" action="{% url 'share' %}" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button class="tweet_btn" type="submit" name="share" style="text-align: center;margin-inline: auto;padding-inline: 15vw;"><i class="fa-solid fa-infinity" style="background-color: rgba(240, 248, 255, 0);"></i>&nbsp;&nbsp;Share</button>
    </form>
</div>

<div style="text-align: right;padding-inline-end: 10px;padding-top: 10px;">
    <a class="tweet_btn" href="{% url 'home' %}" style=" margin-inline-end: 0.5vw; text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward" style="background-color: rgba(0, 0, 0, 0);"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
<script>
 document.addEventListener("DOMContentLoaded", function() {
        let author = document.getElementById("id_author");
        author.value = "{{ user.id }}";
        author.style.display = "none";
        let label = document.querySelector("label[for='id_author']");
        label.style.display = "none";
    });
</script>
{% endblock %}
{% else %}
<script>
    alert(" You do not belong here ");
</script>
<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% endif %}

anonymous/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ANONYMOUS</title>
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome- 
    free@5.15.4/css/fontawesome.min.css">
    
</head>
<body>
    <style>
    *{
        margin: 0;
        color:azure;
        background-color: black;
        box-sizing: border-box;
        transition: all 500ms ease-out;
    }
    .vertical_line{
        min-height: 100vh;
        height: auto;
        border: 1px solid rgba(255, 255, 255, 0.116);
    }
    .horizontal_line{
        position: relative;
        left: -1vw;
        width: 36vw auto;
        border: 1px solid rgba(255, 255, 255, 0.116);
    }
    
    .Home{
        display: flex;
        flex-direction: row;
        width: 80vw;
        padding: 5vw;
        margin-inline: auto;
        padding-top: 0;
    }
    .container_menu{
        width: 20vw;
        text-align: right;
        justify-content: right;
        padding-right: 2vw;
        flex-shrink: 0;
        flex: 0.25;
        border-right:  1px solid rgba(255, 255, 255, 0.473);
        min-height: 100vh;
        height: auto;
        overflow: -moz-hidden-unscrollable;
        position: sticky;
    }
    .container_menu li,.container_menu a,.cats{
        justify-content: space-around;
        margin-inline: 1.5vw auto;
        margin-block-end: 0.2vw;
        padding: 0px;
        border-radius: 20px;
        text-decoration: none;
        list-style: none;
        font-size: 1.5rem;
    }
    ul{
        justify-content: space-around;
        margin-inline: auto;
        margin-block-end: 0.2vw;
        padding: 0px;
        border-radius: 20px;
        text-decoration: none;
        list-style: none;
        font-size: 1.5rem;
    }
    .container_menu a,.cats{
        width: fit-content;
        display: inline-flex;
        padding: 12.5px;
        cursor: pointer;
    }
    .container_menu li,.cats{
        display: flex;
        flex-direction: column;
        align-items: center;
        
    }
    .container_menu a i{
        background-color: rgba(240, 248, 255, 0);
    }
    .container_menu a:hover,.cats:hover{
        background-color: rgba(240, 248, 255, 0.171);
        color: #50b7f5;
        transition: all 100ms ease-out;
    }
    .container_blogs{
    max-width: 46vw;
    min-width: 45vw;
    padding-block-end: 0.5vw;
    /*border: 2px solid rgba(255, 255, 255, 0.116);*/
    justify-content: center;
    border-right:  1px solid rgba(255, 255, 255, 0.473);
    }
    .container_profile{
        width: 25vw;
    }
    .blogpost{
    box-sizing: border-box;
    margin-inline: auto;
    flex: 1;
    padding: 2vw;
    min-width: 44.5vw;
    border-bottom:  1px solid rgba(255, 255, 255, 0.473);
    }
    .blogpost h4{
        font-weight: 800;
        /* font-size: 2rem; */
    }
    .header{
        padding: 6px;
        padding-inline-start: 1vw;
        font-weight: 900;
        font-size: 2rem; 
        position: sticky;
        border-bottom: 1px solid rgba(255, 255, 255, 0.473);
    }
    .menu_opt{
        display: none;
        transition: all 500ms ease-out;
    }
    @media (min-width : 900px) {
        .menu_opt{
        display: block;
        background-color: rgba(240, 248, 255, 0);
    }
    }
    .active a p, .active a i{
        color: #50b7f5;
    }
    body{
        margin-inline: auto;
        display: flex;
    }
    .tweetBox img{
        margin: 0.5vw;
        border-radius: 50%;
        max-height: 40px;
        max-width: 40px;
    }
    .tweetBox{
        padding-bottom: 10px;
        border-bottom: 8px solid rgba(255, 255, 255, 0.473);

    }
    .tweetBox form{
        display: flex;
        flex-direction: column;
        padding: 2px;
    }
    .tweetBox input{
        border: none;
        padding: 20px;
        display: flex;
        flex:1;
    }
    .tweetBox form p{
        border: none;
        padding-top: 5px;
        padding-inline: 0px;
        padding-bottom: 5px;
        display: flex;
        flex:1;
        border-radius: 15px;
        flex-direction: column;
        flex-wrap: wrap;
    }
    .tweetBox #id_title, .tweetBox #id_author , .tweetBox #id_body,.tweetBox #id_categories,.tweetBox #id_name,#id_body{
        border-radius: 10px;
        padding: 5px;
        border: 0.5px solid rgba(255, 255, 255, 0.185);
    }
    #id_body{
        max-width: 49vw;
        margin: 10px;
    }
    .input #file-upload-button{
        padding: 7px;
        border-radius: 15px;
        color: white;
        background-color:#029bfa23;
        border: 0px solid black;
        margin-inline: 6vw;
    }
    .tweetBox li{
        margin-top: 2px;
        padding: 8px;
        padding-bottom: 0px;
        font-size: 1rem;
        color: rgba(240, 248, 255, 0.322);
        background-color: #029bfa00;
    }
    .tweetBox label{
        font-size: 1.5rem;
    }
    .tweet_btn,.like{
        padding: 7px;
        margin-inline: 1vw;
        border-radius: 20px;
        color: white;
        background-color:#029bfa00;
        border: 1px solid rgba(255, 255, 255, 0.274);
        font-size: 1rem;
        text-decoration: none;
    }
    /* .tweet_btn p{
        visibility: hidden;
    }
    .tweet_btn p:hover{
        visibility: visible;
    } */
    .tweet_btn span,.like span{
        background-color: rgba(0, 0, 0, 0);
    }
    .tweet_btn span,.like span{
    transition: all 500ms ease-in-out;
    display: none;
    }

    .tweet_btn:hover span,.like:hover span{
    display: inline;
    }
    .tweet_btn:hover{
        background-color:#029bfa;
    }
    .like:hover,.liked{
        background-color: #ff2d75;
        color: white;
    }
    .kill:hover{
        background-color: red;
        color: white;
    }
    .add:hover{
        background-color:  #5f24ff;
        color: white;
    }
    .booked{
        background-color: white;
        color: black;
    }
    .book:hover{
        background-color: white;
        color: black;
    }
    .book{
        color: black;
    }

    @media (max-width:500px) {
        .container_blogs{
            padding: 5px;
            min-width: 60vw;
        }
        .Home{
            margin-inline-start: 1vw;
            padding-inline-start:0 ;
        }
        .container_menu{
            padding-inline-end: 2.5vw;
        }
        ul{
            margin: 0px auto;
        }
        .icccon a{
            text-align: left;
            font-size: 1rem;
            scale:0.6;
        }
    }
    .deactivate{
        opacity: 0.5;
        pointer-events: none;
    }
    .read:hover{
        color: rgb(255, 255, 255);

    }
    .read{
        color: rgba(250, 235, 215, 0.377);
        transition: all 0.1s ease-in;
        font-weight: 900;
    }

    </style>
    <!-- <h1>GHOSTOO7 & VINNI</h1> -->
    <div class="Home">
        <div class="container_menu">
            <ul>
                <li class="icccon">
                    <a href="" ><i class="fa-solid fa-infinity" style="color: #50b7f5; font-size: 2.25rem;"></i></a>
                </li>
                <li id="homee"class="active">
                    <a href="{% url 'home' %}" class="active" ><i class="fa-solid fa-house-crack"></i><p class="menu_opt">&nbsp;&nbsp;Home</p></a>
                </li>
                {% if user.is_authenticated %}
                <li id="explore">
                    <a href="{% url 'category' 'explore' %}"><i class="fa-solid fa-magnifying-glass"></i><p class="menu_opt">&nbsp;&nbsp;Explore</p></a>
                </li>
                <li id="book">
                    <a href="{% url 'bookmark' user.id %}"><i class="fa-solid fa-book-bookmark"></i><p class="menu_opt">&nbsp;&nbsp;Bookmarks</p></a>
                </li>
                <li id="profile">
                    <a href="{%  url 'profile' user.id %}"><i class="fa-solid fa-id-card"></i><p class="menu_opt">&nbsp;&nbsp;Profile</p></a>
                </li>
                <li>
                    <a href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket" ></i><p class="menu_opt">&nbsp;&nbsp;Logout</p></a>
                </li>
                {% else %}
                <li class="deactivate">
                    <a href=""><i class="fa-solid fa-magnifying-glass"></i><p class="menu_opt">&nbsp;&nbsp;Explore</p></a>
                </li>
                <li class="deactivate">
                    <a href=""><i class="fa-solid fa-book-bookmark"></i><p class="menu_opt">&nbsp;&nbsp;Bookmarks</p></a>
                </li>
                <li>
                    <a href="{%  url 'login' %}"><i class="fa-solid fa-id-card"></i><p class="menu_opt">&nbsp;&nbsp;Login</p></a>
                </li>
                <li>
                    <a href="{% url 'register' %}"><i class="fa-regular fa-square-plus"></i><p class="menu_opt">&nbsp;&nbsp;Register</p></a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="container_blogs">
            <div class="header">
                <header><span id="heading">Home</span></header>
            </div>
            
            <div class="tweetBox">
                <form>
                    <img src="https://images.squarespace-cdn.com/content/v1/5446f93de4b0a3452dfaf5b0/1626904421257-T6I5V5IQ4GI2SJ8EU82M/Above+Avalon+Neil+Cybart">
                    <input type="text" placeholder="Share everything Vinni's Here">
                    {% if user.is_authenticated %}
                    <a class="tweet_btn" href="{% url 'share' %}" style="text-align: center;margin-inline: auto;padding-inline: 15vw;"><i class="fa-solid fa-infinity" style="background-color: rgba(240, 248, 255, 0);"></i>&nbsp;&nbsp;Share</a>
                    {% endif %}
                </form>
            </div>

            {% block content %}

            {% endblock %}
        </div>
        <div class="container_profile">
            {% block profile %}
            {% endblock %}
        </div>
    </div>
    <script>
        const menuItems = document.querySelectorAll('.container_menu li');
        document.querySelector('.container_menu').addEventListener('click', function(event) {
          menuItems.forEach(function(item) {
            item.classList.remove('active');
          });
            const menuItem = document.getElementById("book");
            menuItem.classList.add('active');
        });
        
      </script>
    <script src="https://kit.fontawesome.com/6f691eeda2.js" crossorigin="anonymous"></script>
</body>
</html>

anonymous/templates/delete.html
{% extends 'article_details.html' %}
{% block popup %}
{% if user.is_authenticated %}
{% if user.id == object.author.id %}
<br>
<br>
<hr>
<br>
<div class="popup" style="justify-content: center;">
    <div>
        <p>Are you sure you want to delete this blog ? </p>
        <br>
        <form method="POST">
            {% csrf_token %}

            <button class="tweet_btn" type="submit" name="share" ><i class="fa-solid fa-infinity" style="background-color: rgba(240, 248, 255, 0);"></i>&nbsp;&nbsp;Delete</button>
        </form>
    </div>
</div>

{% else %}
<script>
    alert(" You do not belong here ");
</script>
<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% endif %}
{% else %}
<script>
    alert(" You do not belong here ");
</script>
<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% endif %}
{% endblock %}

anonymous/templates/update.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
{% if user.id == object.author.id %}
<div class="tweetBox" >
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button class="tweet_btn" type="submit" ><i class="fa-solid fa-infinity" style="background-color: rgba(240, 248, 255, 0);"></i>&nbsp;&nbsp;Edit</button>
    </form>
</div>

<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% else %}
<script>
    alert(" You do not belong here ");
</script>
<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% endif %}
{% else %}
<script>
    alert(" You do not belong here ");
</script>
<div style="text-align: right;padding-inline-end: 10px;padding-top: 5px;">
    <a href="{% url 'home' %}" style="text-align: right;font-size: 1rem; color: rgba(250, 235, 215, 0.795);text-decoration: none;"><i class="fa-solid fa-backward"></i>&nbsp;&nbsp;&nbsp;&nbsp;go back</a>
</div>
{% endif %}
{% endblock %}